services:
  cli:
    build:
      context: docker/php
      target: dev
    environment:
      COMPOSER_CACHE_DIR: /home/composer/.cache/composer
      COMPOSER_HOME: /home/composer/.config/composer
      PHP_IDE_CONFIG: serverName=wishlist
      XDEBUG_CONFIG: client_host=172.17.0.1
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    user: ${HOST_USER_IDS:-1000:1000}
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ${HOST_COMPOSER_CACHE_DIR:-~/.cache/composer}
        target: /home/composer/.cache/composer
      - type: bind
        source: ${HOST_COMPOSER_HOME:-~/.config/composer}
        target: /home/composer/.cache/composer
    working_dir: /app

  web:
    image: dunglas/frankenphp:1.12.7-php8.5-trixie
    ports:
      - "${WISHLIST_HTTP_PORT:-80}:80"
      - "${WISHLIST_HTTPS_PORT:-443}:443"
      - "${WISHLIST_HTTPS_PORT:-443}:443/udp"
    volumes:
      - type: bind
        source: .
        target: /app

  database:
    environment:
      POSTGRES_DB: ${PGSQL_DB:-app}
      POSTGRES_USER: ${PGSQL_USERNAME:-app}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD:-password}
    image: postgres:18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 0s
      start_interval: 0s
    ports:
      - "${DEMO_POSTGRE_PORT:-5432}:5432"
    restart: unless-stopped
