x-cache-env-variables: &cache-env-variables
  CYPRESS_CACHE_FOLDER: '/home/cypress-cache'
  YARN_CACHE_FOLDER: '/home/yarn-cache'

x-database-env-variables: &database-env-variables
  DATABASE_URL: 'postgresql://root@database:26257/defaultdb?sslmode=disable'

services:
  node:
    environment:
      <<: [ *cache-env-variables, *database-env-variables ]
    image: 'node:18'
    networks:
      - wishlist
    user: '1000:1000'
    volumes:
      - '.:/srv/app'
      - '${HOST_CYPRESS_CACHE_FOLDER:-~/.cache/Cypress}:/home/cypress-cache'
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/yarn-cache'
      - '${HOST_YARN_CONFIG_FOLDER:-~/.config/yarn}:/.yarn'
      - '${HOST_YARN_CONFIG_FILE:-~/.yarnrc}:/.yarnrc'
    working_dir: '/srv/app'

  dev:
    command:
      - 'yarn'
      - 'dev'
    environment:
      <<: *database-env-variables
    image: 'node:18'
    networks:
      - wishlist
    ports:
      - '3000:3000'
    user: '1000:1000'
    volumes:
      - '.:/srv/app'
    working_dir: '/srv/app'

  prod:
    command:
      - 'yarn'
      - 'start'
    environment:
      <<: *database-env-variables
    image: 'node:lts'
    networks:
      - wishlist
    ports:
      - '8000:3000'
    user: '1000:1000'
    volumes:
      - '.:/srv/app'
    working_dir: '/srv/app'

  cypress-browsers:
    image: 'cypress/browsers:node-18.16.0-chrome-112.0.5615.121-1-ff-112.0.1-edge-112.0.1722.48-1'
    environment:
      <<: *cache-env-variables
      CYPRESS_BASE_URL: 'http://dev:3000'
      DISPLAY: '${DISPLAY}'
    networks:
      - wishlist
    user: '1000:1000'
    volumes:
      - '.:/srv/app'
      - '${HOST_CYPRESS_CACHE_FOLDER:-~/.cache/Cypress}:/home/cypress-cache'
      - '${HOST_YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/yarn-cache'
      - '${HOST_YARN_CONFIG_FOLDER:-~/.yarn}:/.yarn'
      - '${HOST_YARN_CONFIG_FILE:-~/.yarnrc}:/.yarnrc'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
    working_dir: '/srv/app'

  database:
    command: 'start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=localhost'
    image: 'cockroachdb/cockroach'
    ports:
      - '26257:26257'
      - '8080:8080'
    networks:
      - wishlist

networks:
  wishlist:
