version: '3'

silent: true

vars:
  USER_IDS: '{{.USER_IDS| default "1000:1000"}}'

includes:
  build:
    taskfile: ./taskfiles/build.yaml
    aliases: [b]
  database:
    taskfile: ./taskfiles/database.yaml
    aliases: [db]
  dependencies:
    taskfile: ./taskfiles/dependencies.yaml
    aliases: [d]
  run:
    taskfile: ./taskfiles/run.yaml
    aliases: [r]
  tests:
    taskfile: ./taskfiles/tests.yaml
    aliases: [t]

tasks:
  default:
    cmds:
      - task --list
