version: '3'

silent: true

includes:
  database:
    taskfile: ./taskfiles/database.yaml
    aliases: [db]
  dependencies:
    taskfile: ./taskfiles/dependencies.yaml
    aliases: [d]
  tests:
    taskfile: ./taskfiles/tests.yaml
    aliases: [t]

tasks:
  default:
    cmds:
      - task --list

  down:
    cmds:
      - docker compose down -v --remove-orphans
    desc: Stop and remove all containers

  run:
    cmds:
      - docker compose run --rm --remove-orphans app {{.CLI_ARGS}}
    desc: "Run something in the app container. Example: task run -- bin/console"

  up:
    cmds:
      - task: dependencies:install
      - task: database:up
      - task: database:migrate
      - task: database:test:create
    desc: Start and set up the application
