version: 3

tasks:
  dev:
    aliases:
      - d
    cmds:
      - docker compose pull
      - docker compose build --pull
    desc: Build the development image

  prod:
    aliases:
      - p
    cmds:
      - docker build --tag carcel/wishlist:latest --target frankenphp_prod .
    desc: Build the production image
