version: 3

tasks:
  up:
    aliases:
      - u
    cmds:
      - docker compose up -d --wait database
    desc: Start the database container

  test:create:
    aliases:
      - t:c
      - test:c
      - t:create
    cmds:
      - docker compose run --rm -e APP_ENV=test cli bin/console doctrine:database:create --if-not-exists
      - task: migrate
        vars:
          APP_ENV: test
    desc: Create the test database (the "regular" database is created automatically at container startup)

  migrate:
    aliases:
      - m
    cmds:
      - docker compose run --rm -e APP_ENV="{{.APP_ENV}}" cli bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
    desc: Run database migrations
    vars:
      APP_ENV: '{{.APP_ENV| default "dev"}}'
