#index:
#    path: /
#    controller: App\Controller\DefaultController::index

kernel:
    resource: ../src/Kernel.php
    type: annotation

# API routes

get_wishlists:
    path: /api/wishlists
    controller: App\Infrastructure\WishList\UserInterface\Web\WishLists
    methods: GET
